#!/usr/bin/env bash
# Render repo MD documents → styled standalone HTML for the coverage hub (/v1/docs/).
# Called by scripts/build-deploy.sh; runnable standalone.
# Deps: bun (md2html.ts) + python3 (stdlib link post-fix). No npm/pip packages.
# (System pandoc exists but is broken — missing libHS* libs — hence md2html.ts.)
#
# THE GENERATING CODE LIVES HERE ON PURPOSE (preserve-creation-code rule):
# the HTML files in this dir are build artifacts, regenerated by this script.
set -euo pipefail
cd "$(dirname "$0")"

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || { cd ../../..; pwd; })"
DOCS="$ROOT/docs"

# slug|source|title
SPECS="
01_BUSINESS_ANALYSIS|01_BUSINESS_ANALYSIS.md|Business Analysis
02_MASTER_PLAN|02_MASTER_PLAN.md|Master Plan
15_BLOCKERS|15_BLOCKERS.md|Blockers
17_FEATURES_AND_PROGRESS|17_FEATURES_AND_PROGRESS.md|Features & Progress
19_PRICING_EQUITY_GUIDE|19_PRICING_EQUITY_GUIDE.md|Pricing & Equity Guide
21_BEEPER_MATRIX_INVESTIGATION|21_BEEPER_MATRIX_INVESTIGATION.md|Beeper/Matrix Investigation
22_BACKEND_CHAT_ARCHITECTURE|22_BACKEND_CHAT_ARCHITECTURE.md|Backend Chat Architecture
24_GAME_DESIGN|24_GAME_DESIGN.md|Game Design
25_DESIGN_BRIEF|25_DESIGN_BRIEF.md|Design Brief
figma_design_analysis|$ROOT/figma/notes/analysis.md|Figma Design Analysis
"

echo "$SPECS" | while IFS='|' read -r slug src title; do
  [ -z "$slug" ] && continue
  src_path="$DOCS/$src"
  [ -f "$src_path" ] || src_path="$src"   # absolute-path spec (figma analysis)
  bun md2html.ts "$src_path" "$title" "$slug"
done

# Post-fix links (python3 stdlib):
#   1. hrefs to rendered sibling docs (XX_*.md, ../figma/notes/analysis.md) → .html
#   2. hrefs to NON-rendered repo docs → unwrapped to plain text (no dead links)
python3 - <<'PY'
import re, pathlib

rendered = {
    "01_BUSINESS_ANALYSIS.md", "02_MASTER_PLAN.md", "15_BLOCKERS.md",
    "17_FEATURES_AND_PROGRESS.md", "19_PRICING_EQUITY_GUIDE.md",
    "21_BEEPER_MATRIX_INVESTIGATION.md", "22_BACKEND_CHAT_ARCHITECTURE.md",
    "24_GAME_DESIGN.md", "25_DESIGN_BRIEF.md", "analysis.md",
}

anchor = re.compile(r'<a href="([^"]+)"[^>]*>(.*?)</a>', re.S)

def target_for(name: str) -> str | None:
    """Rendered output filename for a referenced .md, or None if not shipped."""
    if name == "analysis.md":
        return "figma_design_analysis.html"
    if name in rendered:
        return name[:-3] + ".html"
    return None

for f in pathlib.Path(".").glob("*.html"):
    if f.name == "template.html":
        continue
    html = f.read_text()
    def sub(m):
        href, text = m.group(1), m.group(2)
        if href.endswith(".md"):
            tgt = target_for(href.split("/")[-1])
            if tgt:
                return f'<a href="{tgt}">{text}</a>'
            return text  # not shipped — keep the words, drop the dead link
        return m.group(0)
    out = anchor.sub(sub, html)
    if out != html:
        f.write_text(out)
        print(f"▸ links fixed: {f.name}")
PY

echo "▸ done: $(ls *.html | grep -v template | wc -l) documents rendered"
