#!/usr/bin/env python3
"""
Build the RWF follow-up pitch deck + appendix PDFs.

What this does (no new deps; python3 + chromium only):
  1. Base64-inlines Space Grotesk + Anton from design/fonts/ into
     docs/pitchdeck/fonts-embed.css (so the HTML source stays hand-editable
     and the PDFs embed real vector text in the brand fonts).
  2. Serves the repo root on a local HTTP port (avoids file:// asset
     restrictions).
  3. Prints docs/pitchdeck/deck.html     -> docs/RWF_Followup_Deck.pdf    (16:9, 1280x720 pages)
     and   docs/pitchdeck/appendix.html -> docs/RWF_Followup_Appendix.pdf (A4 portrait pages)
     via headless Chromium --print-to-pdf.

Usage:  python3 docs/pitchdeck/build.py
"""

import base64
import http.server
import os
import socket
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))  # repo root
DOCS = os.path.join(ROOT, "docs")

FONT_SOURCES = [
    (
        "SpaceGrotesk",
        os.path.join(ROOT, "design/fonts/sg-var.woff2"),
        "woff2",
        "variable",
    ),
    (
        "Anton",
        os.path.join(ROOT, "design/fonts/anton-regular.woff2"),
        "woff2",
        "normal",
    ),
]


def build_fonts_css() -> str:
    rules = []
    for family, path, fmt, weight in FONT_SOURCES:
        with open(path, "rb") as f:
            b64 = base64.b64encode(f.read()).decode("ascii")
        rules.append(
            "@font-face{font-family:'%s';font-style:normal;font-weight:%s;"
            "src:url(data:font/%s;base64,%s) format('%s');}"
            % (family, ("100 900" if weight == "variable" else "400"), fmt, b64, fmt)
        )
    css = "/* GENERATED by docs/pitchdeck/build.py — do not edit by hand.\n"
    css += "   Base64-inlined from design/fonts/ so PDFs embed brand type. */\n"
    css += "\n".join(rules) + "\n"
    out = os.path.join(HERE, "fonts-embed.css")
    with open(out, "w") as f:
        f.write(css)
    return out


def free_port() -> int:
    s = socket.socket()
    s.bind(("127.0.0.1", 0))
    port = s.getsockname()[1]
    s.close()
    return port


class Quiet(http.server.SimpleHTTPRequestHandler):
    def log_message(self, format, *args):  # silence  # noqa: A002
        pass


def print_pdf(url: str, out_path: str) -> None:
    cmd = [
        "/usr/bin/chromium",
        "--headless=new",
        "--disable-gpu",
        "--disable-dev-shm-usage",
        "--hide-scrollbars",
        "--no-pdf-header-footer",
        "--user-data-dir=/tmp/rwf-pdf-profile",
        "--virtual-time-budget=25000",
        f"--print-to-pdf={out_path}",
        url,
    ]
    print("  chromium:", os.path.basename(out_path))
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=180, cwd=ROOT)
    if r.returncode != 0:
        sys.stderr.write(r.stdout + r.stderr)
        raise SystemExit(f"chromium failed for {out_path}")
    size = os.path.getsize(out_path)
    if size < 100_000:
        raise SystemExit(
            f"{out_path} suspiciously small ({size} bytes) — images may be missing"
        )


def main() -> None:
    css = build_fonts_css()
    print("wrote", css)
    port = free_port()
    httpd = http.server.ThreadingHTTPServer(("127.0.0.1", port), Quiet)
    import threading

    t = threading.Thread(target=httpd.serve_forever, daemon=True)
    t.start()
    time.sleep(0.5)
    try:
        base = f"http://127.0.0.1:{port}"
        print_pdf(
            f"{base}/docs/pitchdeck/deck.html",
            os.path.join(DOCS, "RWF_Followup_Deck.pdf"),
        )
        print_pdf(
            f"{base}/docs/pitchdeck/appendix.html",
            os.path.join(DOCS, "RWF_Followup_Appendix.pdf"),
        )
    finally:
        httpd.shutdown()
    for f in ("RWF_Followup_Deck.pdf", "RWF_Followup_Appendix.pdf"):
        p = os.path.join(DOCS, f)
        print(f"{f}: {os.path.getsize(p) / 1024:.0f} KB")
    print("done.")


if __name__ == "__main__":
    main()
