#!/usr/bin/env python3
"""
make_icons.py — generates the Reps With Friends launcher icon set.

Glyph source: the inline SVG dumbbell from site/index.html (guide launcher),
a 24x24 viewBox of five rounded rects, rendered lime #c6f32e on dark #0a0b0d.

Outputs (relative to apps/android/):
  app/src/main/res/drawable/ic_launcher_background.xml  (dark adaptive bg)
  app/src/main/res/drawable/ic_launcher_foreground.xml  (vector glyph, 108dp)
  app/src/main/res/mipmap-{mdpi,hdpi,xhdpi,xxhdpi,xxxhdpi}/ic_launcher.png
  app/src/main/res/mipmap-{...}/ic_launcher_round.png

The adaptive foreground maps the 24-unit glyph into the 66x66dp safe zone of
the 108dp canvas (scale = 66/24 = 2.75, translate = 21). The farthest glyph
corner from centre is ~8.3 units (-> ~22.9dp scaled), comfortably inside the
33dp-radius safe circle.

Run from anywhere:  python3 apps/android/scripts/make_icons.py
"""

from pathlib import Path

from PIL import Image, ImageDraw

BRAND_BG = (10, 11, 13, 255)  # #0a0b0d
BRAND_LIME = (198, 243, 46, 255)  # #c6f32e

# (x, y, w, h, rx) in the site's 24x24 viewBox — copied from site/index.html
GLYPH_RECTS = [
    (1.0, 10.7, 3.2, 2.6, 1.1),  # outer left plate
    (4.6, 8.2, 3.4, 7.6, 1.2),  # inner left plate
    (8.6, 11.0, 6.8, 2.0, 1.0),  # bar
    (16.0, 8.2, 3.4, 7.6, 1.2),  # inner right plate
    (19.8, 10.7, 3.2, 2.6, 1.1),  # outer right plate
]

RES = Path(__file__).resolve().parent.parent / "app" / "src" / "main" / "res"

MIPMAP_DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}


def rounded_rect_path(x: float, y: float, w: float, h: float, r: float) -> str:
    """Rounded rect as SVG/VectorDrawable pathData (clockwise from top-left)."""
    xr, yb = x + r, y + h - r
    return (
        f"M {x + r},{y} H {x + w - r} A {r},{r} 0 0 1 {x + w},{y + r} "
        f"V {yb} A {r},{r} 0 0 1 {x + w - r},{y + h} "
        f"H {x + r} A {r},{r} 0 0 1 {x},{yb} "
        f"V {y + r} A {r},{r} 0 0 1 {x + r},{y} Z"
    )


def write_background_xml() -> None:
    out = RES / "drawable" / "ic_launcher_background.xml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by scripts/make_icons.py — do not edit by hand. -->\n"
        '<shape xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <solid android:color="#0a0b0d" />\n'
        "</shape>\n"
    )
    print(f"wrote {out}")


def write_foreground_xml() -> None:
    scale = 66.0 / 24.0  # map the 24-unit glyph onto the 66dp safe zone
    translate = (108.0 - 66.0) / 2.0  # 21
    paths = "\n".join(
        f'        <path android:fillColor="#c6f32e"\n'
        f'              android:pathData="{rounded_rect_path(*rect)}" />'
        for rect in GLYPH_RECTS
    )
    out = RES / "drawable" / "ic_launcher_foreground.xml"
    out.write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by scripts/make_icons.py from the site/index.html dumbbell glyph. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp"\n'
        '    android:height="108dp"\n'
        '    android:viewportWidth="108"\n'
        '    android:viewportHeight="108">\n'
        f'    <group android:translateX="{translate}" android:translateY="{translate}"\n'
        f'           android:scaleX="{scale}" android:scaleY="{scale}">\n'
        f"{paths}\n"
        "    </group>\n"
        "</vector>\n"
    )
    print(f"wrote {out}")


def draw_glyph(
    draw: ImageDraw.ImageDraw, canvas: int, offset: float, scale: float
) -> None:
    for x, y, w, h, r in GLYPH_RECTS:
        x0 = offset + x * scale
        y0 = offset + y * scale
        x1 = offset + (x + w) * scale
        y1 = offset + (y + h) * scale
        draw.rounded_rectangle([x0, y0, x1, y1], radius=r * scale, fill=BRAND_LIME)


def write_mipmaps() -> None:
    for density, size in MIPMAP_DENSITIES.items():
        d = RES / f"mipmap-{density}"
        d.mkdir(parents=True, exist_ok=True)

        # Same proportions as the adaptive icon: glyph box = 66/108 of canvas.
        scale = size * (66.0 / 108.0) / 24.0
        offset = size * ((108.0 - 66.0) / 2.0) / 108.0

        # Square legacy icon — full-bleed dark bg.
        img = Image.new("RGBA", (size, size), BRAND_BG)
        draw_glyph(ImageDraw.Draw(img), size, offset, scale)
        img.save(d / "ic_launcher.png")

        # Round legacy icon — dark circle, glyph scaled 0.9x for optical safety.
        img_r = Image.new("RGBA", (size, size), (0, 0, 0, 0))
        d_r = ImageDraw.Draw(img_r)
        d_r.ellipse([0, 0, size - 1, size - 1], fill=BRAND_BG)
        draw_glyph(d_r, size, offset, scale * 0.92)
        img_r.save(d / "ic_launcher_round.png")

        print(f"wrote {d}/ic_launcher.png + ic_launcher_round.png ({size}x{size})")


if __name__ == "__main__":
    write_background_xml()
    write_foreground_xml()
    write_mipmaps()
    print("done.")
