#!/usr/bin/env python3
"""vendor_library.py — resolve the style library into ONE self-contained CSS.

apps/figma-app vendors design/themes.css as a single file (sw.js caches
"./themes.css" as one asset), but themes.css now @imports the portable
library. This script resolves the import chain (base + every theme file,
in index.css order) and writes the flattened result:

    python3 scripts/styles/vendor_library.py            # → apps/figma-app/themes.css

build-deploy.sh runs it on every build so the vendored copy can never drift
from the library. Pure stdlib; no deps.
"""

from __future__ import annotations
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
LIB = ROOT / "design" / "style-library"
THEMES = ROOT / "design" / "themes.css"
OUT = ROOT / "apps" / "figma-app" / "themes.css"

IMPORT_RE = re.compile(r'^@import\s+url\("([^"]+)"\);')


def resolve(css: str, base: pathlib.Path, seen: list[str]) -> str:
    out = []
    for line in css.splitlines():
        m = IMPORT_RE.match(line.strip())
        if m:
            target = base / m.group(1)
            seen.append(str(target.relative_to(ROOT)))
            out.append(resolve(target.read_text(), target.parent, seen).rstrip())
        else:
            out.append(line)
    return "\n".join(out)


def main() -> int:
    seen: list[str] = []
    resolved = resolve(THEMES.read_text(), THEMES.parent, seen)
    banner = (
        "/* GENERATED by scripts/styles/vendor_library.py — design/themes.css\n"
        "   with the style-library import chain RESOLVED to one file.\n"
        "   Do not hand-edit; edit design/style-library/* + design/themes.css\n"
        "   and re-run the vendor script (build-deploy.sh does this too).\n"
        "   Resolved chain:\n" + "".join(f"     · {s}\n" for s in seen) + "*/\n"
    )
    OUT.write_text(banner + resolved.lstrip() + "\n")
    rules = resolved.count("{") - resolved.count("}")
    print(
        f"vendored → {OUT.relative_to(ROOT)} ({len(seen)} imports resolved, {rules} rules)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
