#!/usr/bin/env bash
# Assemble the Cloudflare Pages deploy bundle from the monorepo.
# Output: deploy/ (site at /, app at /app, hub at /hub, debug at /debug,
# design at /design, functions for /api/ai + /api/state).
set -euo pipefail
cd "$(dirname "$0")/.."

echo "▸ building app bundle"
bun build apps/web/src/main.ts --outdir apps/web/dist --minify >/dev/null

echo "▸ assembling deploy/public (functions/ lives beside it — wrangler picks it up from cwd)"
mkdir -p deploy/public/site deploy/public/design deploy/public/app deploy/public/hub deploy/public/debug deploy/public/slack deploy/public/connect deploy/public/demo deploy/public/system deploy/public/cards deploy/public/figma-app deploy/public/wiki

cp site/index.html deploy/public/index.html
cp site/*.css site/*.js deploy/public/site/
cp -r site/lib deploy/public/site/lib
# hub thumbnails — version-card shots for the main-page hub (resized app
# screenshots; source-of-truth + provenance in site/hub-shots/README.md)
mkdir -p deploy/public/site/hub-shots && cp site/hub-shots/*.png deploy/public/site/hub-shots/
cp -r design/. deploy/public/design/
cp -r apps/web/dist/. deploy/public/app/
cp apps/hub/index.html apps/hub/hub.js apps/hub/hub.css deploy/public/hub/
cp apps/debug/index.html apps/debug/debug.js apps/debug/debug.css deploy/public/debug/
cp apps/slack-setup/index.html apps/slack-setup/slack-setup.js apps/slack-setup/slack-setup.css apps/slack-setup/manifest.yml deploy/public/slack/
cp apps/connect/index.html apps/connect/connect.js apps/connect/connect.css apps/connect/qr.js deploy/public/connect/
cp apps/demo/index.html apps/demo/demo.js apps/demo/demo.css deploy/public/demo/
cp apps/systempage/index.html apps/systempage/system.js apps/systempage/system.css deploy/public/system/
# theme exploration gallery (design/themes.css rides the existing design/ copy)
mkdir -p deploy/public/styles && cp apps/styles/index.html apps/styles/demo.html apps/styles/appdemo.html apps/styles/styles.css apps/styles/gallery.js apps/styles/verify.js deploy/public/styles/
# sfx demo — the /sfx link (live app sound catalogue; defensive one-file copy
# of the figma-app synthesis module — see apps/sfx-demo/sfx.js header)
mkdir -p deploy/public/sfx && cp apps/sfx-demo/index.html apps/sfx-demo/sfx.js deploy/public/sfx/
# ── figma-app version stamp (v1.0.0) ────────────────────────────────────
# the app vendors a copy of design/themes.css (theme beta) — sync it so the
# five skins can never drift between the gallery and the app
# design/themes.css now imports the portable style library — vendor it
# RESOLVED to one self-contained file (sw.js caches themes.css as one asset;
# unresolved @imports would 404 inside /figma-app).
python3 scripts/styles/vendor_library.py
# sw.js derives its cache name from version.js's BUILD_STAMP, so EVERY
# deploy busts the service-worker cache — the stale-SW phone bug stays
# dead. git hash alone isn't enough (multiple deploys per commit), so the
# stamp also carries the UTC build minute.
RWF_VER="1.0.0"
RWF_HASH="$(git rev-parse --short HEAD 2>/dev/null || echo 'nogit')"
RWF_STAMP="$(date -u +%Y%m%d%H%M)"
cat > apps/figma-app/version.js <<VEOF
/* GENERATED by scripts/build-deploy.sh — do not hand-edit.
   sw.js derives its cache name from BUILD_STAMP (stale-cache fix);
   the About screen surfaces the same values. */
export const APP_VERSION = "${RWF_VER}";
export const BUILD_HASH = "${RWF_HASH}";
export const BUILD_DATE = "$(date -u +%Y-%m-%d)";
export const BUILD_STAMP = "${RWF_VER}+${RWF_HASH}.${RWF_STAMP}";
VEOF
echo "▸ stamped figma-app v${RWF_VER} · ${RWF_HASH} · ${RWF_STAMP}"
# offline Figma test app (Ben's design, every screen — self-contained, SW-cached)
# Ship the app, not the test scaffolding: shots/ (31 PNGs ~2MB), e2e/bots
# scripts and engine tests stay local.
find apps/figma-app -maxdepth 1 -type f \( -name "*.html" -o -name "*.js" -o -name "*.css" \
  -o -name "*.json" -o -name "*.svg" -o -name "*.png" -o -name "*.webmanifest" \) \
  -exec cp {} deploy/public/figma-app/ \;
for d in apps/figma-app/*/; do
  case "$(basename "$d")" in shots|test|node_modules) ;; *) cp -r "$d" deploy/public/figma-app/ ;; esac
done
# wiki (living documentation — self-contained incl. shots; test/ scaffolding stays local)
find apps/wiki -maxdepth 1 -type f \( -name "*.html" -o -name "*.css" -o -name "*.js" \) \
  -exec cp {} deploy/public/wiki/ \;
cp -r apps/wiki/shots deploy/public/wiki/shots

# deploy/functions/api/{ai,state}.js are source-controlled as-is

echo "▸ bundle ready:"
find deploy/public -type f | wc -l | xargs echo "  asset files:"
du -sh deploy/public | cut -f1 | xargs echo "  size:"
echo "  deploy with: cd deploy && bunx wrangler pages deploy public --project-name=rwf"

# founder follow-up deck (PDFs for Ben)
mkdir -p deploy/public/deck
cp docs/RWF_Followup_Deck.pdf docs/RWF_Followup_Appendix.pdf deploy/public/deck/ 2>/dev/null || true
# contract & scope PDF — copy-if-missing (idempotent; never clobbers a newer copy)
for pdf in RWF_Contract_Scope.pdf; do
  if [ -f "docs/$pdf" ] && [ ! -f "deploy/public/deck/$pdf" ]; then
    cp "docs/$pdf" deploy/public/deck/
  fi
done

# ── Ben's Pinterest ideation wall (the /pinboard link) ────────────────
# Design reference wall from Ben Gillies' shared board (internal only).
# shots/ (verification screenshots) stay local, like figma-app's.
mkdir -p deploy/public/pinboard
cp site/pinboard/index.html site/pinboard/pinboard.css site/pinboard/pinboard.js \
   site/pinboard/manifest.json site/pinboard/README.md deploy/public/pinboard/
cp site/pinboard/pin_*.jpg site/pinboard/pin_*.png deploy/public/pinboard/ 2>/dev/null || true

# android APK for manual install
mkdir -p deploy/public/apk
cp apps/android/app/build/outputs/apk/debug/app-debug.apk deploy/public/apk/rwf-app-debug.apk 2>/dev/null || true

# ── v2 board app (track-and-field board game) — the /v2 link ────────
# Independent fork of the v1 engine; shots/ + e2e stay local (like figma-app).
mkdir -p deploy/public/v2
find apps/board -maxdepth 1 -type f \( -name "*.html" -o -name "*.js" -o -name "*.css" \) \
  -exec cp {} deploy/public/v2/ \;

# ── v3 battle course (3D) — the /v3 link ────────────────────────────
# The founder's real vision: Geno mocap runners on a 3D course, power-up
# cards over every player, the charity pot at the finish. Engine forked
# from board (v2). App files only — shots/ + e2e stay local; three.js +
# models ride the existing /site/lib + /models deploy copies below.
mkdir -p deploy/public/v3
find apps/v3 -maxdepth 1 -type f \( -name "*.html" -o -name "*.js" -o -name "*.css" \) \
  -exec cp {} deploy/public/v3/ \;

# ── v4 SoT app (the Source of Truth app) — the /v4 link ──────────────
# Daily battle to a 200-adjusted-rep target · first-to-target Daily Win
# (battle continues, later finishers bank the day) · weekly seasons ·
# stakes incl. charity pot · SOT power-up canon. App files + vendored
# fonts only — shots/ + e2e stay local (same convention as v2/v3).
# The shared daily-battle engine (apps/sot-engine.js) ships beside the
# app: index.html loads it first and apps/sot/engine.js hard-requires it.
mkdir -p deploy/public/v4/fonts
find apps/sot -maxdepth 1 -type f \( -name "*.html" -o -name "*.js" -o -name "*.css" \) \
  -exec cp {} deploy/public/v4/ \;
cp apps/sot/fonts/*.woff2 deploy/public/v4/fonts/
cp apps/sot-engine.js deploy/public/v4/sot-engine.js

# ── v1 coverage hub (v1.1.0) — the share page at rwf.qalarc.com/v1 ─────
# One page linking every live surface, dashboard and business document.
# shots/ (verification screenshots) stay local, like figma-app's.
mkdir -p deploy/public/v1
find apps/hub-public -maxdepth 1 -type f \( -name "*.html" -o -name "*.css" \) \
  -exec cp {} deploy/public/v1/ \;
mkdir -p deploy/public/v1/assets && cp apps/hub-public/assets/* deploy/public/v1/assets/
mkdir -p deploy/public/v1/docs
find apps/hub-public/docs -maxdepth 1 -type f \( -name "*.html" -o -name "*.css" \) \
  ! -name "template.html" -exec cp {} deploy/public/v1/docs/ \;

# ── avatar gallery + outfit atelier (the /avatars and /atelier links) ──
# Model assets are SELECTIVE: site/models also holds ~300MB of meshy.ai
# experiment artifacts that never ship. Cloudflare Pages caps a single
# file at 25 MiB, so goblin_walk_stick.bvh (32M) stays local — its card
# degrades gracefully at runtime (fetch fails, others load).
mkdir -p deploy/public/avatars deploy/public/atelier
cp apps/avatars/index.html apps/avatars/avatars.js apps/avatars/avatars.css deploy/public/avatars/
cp apps/atelier/index.html apps/atelier/atelier.js apps/atelier/atelier.css deploy/public/atelier/
mkdir -p deploy/public/models deploy/public/models/meshy \
         deploy/public/site/models deploy/public/site/avatar-styles
for f in orc.glb orc_marauder.glb Soldier.glb Xbot.glb Geno.glb Cranberry.glb \
         wolf.glb dragon_hunter.glb dragon_elder.glb \
         humanoid_adventurer.glb humanoid_brute.glb \
         meshy_frog_full.glb meshy_frog_head_b.glb meshy_frog_head_c.glb \
         goblin_limp.bvh goblin_drag.bvh goblin_one_arm.bvh goblin_combat.bvh; do
  cp "site/models/$f" deploy/public/models/ 2>/dev/null || echo "  (skip $f — not found)"
done
cp site/models/geno_npz_*.json deploy/public/models/
cp site/models/meshy/manifest.json deploy/public/models/meshy/
cp site/models/*.js deploy/public/site/models/
cp site/avatar-styles/*.js deploy/public/site/avatar-styles/

# ── photo booth (selfie → stylised bust; the /booth link) ──────────────
# Generation runs on the LOCAL machine only (python harness + chromium gate +
# server-side keys — /api/booth exists just on the dev server). The deployed
# page detects the missing API and shows the honest local-only notice; busts
# generated locally still display via the photo_avatars copy below.
mkdir -p deploy/public/booth
cp apps/booth/index.html apps/booth/booth.css apps/booth/booth.js apps/booth/gate.html deploy/public/booth/
# photo avatars + booth busts (code-only, KBs each): the /avatars photo strip
# loads them from /site/models/photo_avatars/, incl. the booth registry JSON.
cp -r site/models/photo_avatars deploy/public/site/models/photo_avatars
