#!/usr/bin/env bash
# Assemble the Cloudflare Pages deploy bundle from the monorepo.
# Output: deploy/ (site at /, app at /app, hub at /hub, debug at /debug,
# design at /design, functions for /api/ai + /api/state).
set -euo pipefail
cd "$(dirname "$0")/.."

echo "▸ building app bundle"
bun build apps/web/src/main.ts --outdir apps/web/dist --minify >/dev/null

echo "▸ assembling deploy/public (functions/ lives beside it — wrangler picks it up from cwd)"
mkdir -p deploy/public/site deploy/public/design deploy/public/app deploy/public/hub deploy/public/debug deploy/public/slack deploy/public/connect deploy/public/demo deploy/public/system deploy/public/cards deploy/public/figma-app deploy/public/wiki

cp site/index.html deploy/public/index.html
cp site/*.css site/*.js deploy/public/site/
cp -r site/lib deploy/public/site/lib
cp -r design/. deploy/public/design/
cp -r apps/web/dist/. deploy/public/app/
cp apps/hub/index.html apps/hub/hub.js apps/hub/hub.css deploy/public/hub/
cp apps/debug/index.html apps/debug/debug.js apps/debug/debug.css deploy/public/debug/
cp apps/slack-setup/index.html apps/slack-setup/slack-setup.js apps/slack-setup/slack-setup.css apps/slack-setup/manifest.yml deploy/public/slack/
cp apps/connect/index.html apps/connect/connect.js apps/connect/connect.css apps/connect/qr.js deploy/public/connect/
cp apps/demo/index.html apps/demo/demo.js apps/demo/demo.css deploy/public/demo/
cp apps/systempage/index.html apps/systempage/system.js apps/systempage/system.css deploy/public/system/
# theme exploration gallery (design/themes.css rides the existing design/ copy)
mkdir -p deploy/public/styles && cp apps/styles/index.html apps/styles/demo.html apps/styles/styles.css apps/styles/gallery.js apps/styles/verify.js deploy/public/styles/
# ── figma-app version stamp (v1.0.0) ────────────────────────────────────
# the app vendors a copy of design/themes.css (theme beta) — sync it so the
# five skins can never drift between the gallery and the app
cp design/themes.css apps/figma-app/themes.css
# sw.js derives its cache name from version.js's BUILD_STAMP, so EVERY
# deploy busts the service-worker cache — the stale-SW phone bug stays
# dead. git hash alone isn't enough (multiple deploys per commit), so the
# stamp also carries the UTC build minute.
RWF_VER="1.0.0"
RWF_HASH="$(git rev-parse --short HEAD 2>/dev/null || echo 'nogit')"
RWF_STAMP="$(date -u +%Y%m%d%H%M)"
cat > apps/figma-app/version.js <<VEOF
/* GENERATED by scripts/build-deploy.sh — do not hand-edit.
   sw.js derives its cache name from BUILD_STAMP (stale-cache fix);
   the About screen surfaces the same values. */
export const APP_VERSION = "${RWF_VER}";
export const BUILD_HASH = "${RWF_HASH}";
export const BUILD_DATE = "$(date -u +%Y-%m-%d)";
export const BUILD_STAMP = "${RWF_VER}+${RWF_HASH}.${RWF_STAMP}";
VEOF
echo "▸ stamped figma-app v${RWF_VER} · ${RWF_HASH} · ${RWF_STAMP}"
# offline Figma test app (Ben's design, every screen — self-contained, SW-cached)
# Ship the app, not the test scaffolding: shots/ (31 PNGs ~2MB), e2e/bots
# scripts and engine tests stay local.
find apps/figma-app -maxdepth 1 -type f \( -name "*.html" -o -name "*.js" -o -name "*.css" \
  -o -name "*.json" -o -name "*.svg" -o -name "*.png" -o -name "*.webmanifest" \) \
  -exec cp {} deploy/public/figma-app/ \;
for d in apps/figma-app/*/; do
  case "$(basename "$d")" in shots|test|node_modules) ;; *) cp -r "$d" deploy/public/figma-app/ ;; esac
done
# wiki (living documentation — self-contained incl. shots; test/ scaffolding stays local)
find apps/wiki -maxdepth 1 -type f \( -name "*.html" -o -name "*.css" -o -name "*.js" \) \
  -exec cp {} deploy/public/wiki/ \;
cp -r apps/wiki/shots deploy/public/wiki/shots

# deploy/functions/api/{ai,state}.js are source-controlled as-is

echo "▸ bundle ready:"
find deploy/public -type f | wc -l | xargs echo "  asset files:"
du -sh deploy/public | cut -f1 | xargs echo "  size:"
echo "  deploy with: cd deploy && bunx wrangler pages deploy public --project-name=rwf"

# founder follow-up deck (PDFs for Ben)
mkdir -p deploy/public/deck
cp docs/RWF_Followup_Deck.pdf docs/RWF_Followup_Appendix.pdf deploy/public/deck/ 2>/dev/null || true
# contract & scope PDF — copy-if-missing (idempotent; never clobbers a newer copy)
for pdf in RWF_Contract_Scope.pdf; do
  if [ -f "docs/$pdf" ] && [ ! -f "deploy/public/deck/$pdf" ]; then
    cp "docs/$pdf" deploy/public/deck/
  fi
done

# android APK for manual install
mkdir -p deploy/public/apk
cp apps/android/app/build/outputs/apk/debug/app-debug.apk deploy/public/apk/rwf-app-debug.apk 2>/dev/null || true

# ── v2 board app (poker-table × track battle) — the /v2 link ──────────
# Independent fork of the v1 engine; shots/ + e2e stay local (like figma-app).
mkdir -p deploy/public/v2
find apps/board -maxdepth 1 -type f \( -name "*.html" -o -name "*.js" -o -name "*.css" \) \
  -exec cp {} deploy/public/v2/ \;

# ── v1 coverage hub (v1.1.0) — the share page at rwf.qalarc.com/v1 ─────
# One page linking every live surface, dashboard and business document.
# shots/ (verification screenshots) stay local, like figma-app's.
mkdir -p deploy/public/v1
find apps/hub-public -maxdepth 1 -type f \( -name "*.html" -o -name "*.css" \) \
  -exec cp {} deploy/public/v1/ \;
mkdir -p deploy/public/v1/assets && cp apps/hub-public/assets/* deploy/public/v1/assets/
mkdir -p deploy/public/v1/docs
find apps/hub-public/docs -maxdepth 1 -type f \( -name "*.html" -o -name "*.css" \) \
  ! -name "template.html" -exec cp {} deploy/public/v1/docs/ \;

# ── avatar gallery + outfit atelier (the /avatars and /atelier links) ──
# Model assets are SELECTIVE: site/models also holds ~300MB of meshy.ai
# experiment artifacts that never ship. Cloudflare Pages caps a single
# file at 25 MiB, so goblin_walk_stick.bvh (32M) stays local — its card
# degrades gracefully at runtime (fetch fails, others load).
mkdir -p deploy/public/avatars deploy/public/atelier
cp apps/avatars/index.html apps/avatars/avatars.js apps/avatars/avatars.css deploy/public/avatars/
cp apps/atelier/index.html apps/atelier/atelier.js apps/atelier/atelier.css deploy/public/atelier/
mkdir -p deploy/public/models deploy/public/models/meshy \
         deploy/public/site/models deploy/public/site/avatar-styles
for f in orc.glb orc_marauder.glb Soldier.glb Xbot.glb Geno.glb Cranberry.glb \
         wolf.glb dragon_hunter.glb dragon_elder.glb \
         humanoid_adventurer.glb humanoid_brute.glb \
         meshy_frog_full.glb meshy_frog_head_b.glb meshy_frog_head_c.glb \
         goblin_limp.bvh goblin_drag.bvh goblin_one_arm.bvh goblin_combat.bvh; do
  cp "site/models/$f" deploy/public/models/ 2>/dev/null || echo "  (skip $f — not found)"
done
cp site/models/geno_npz_*.json deploy/public/models/
cp site/models/meshy/manifest.json deploy/public/models/meshy/
cp site/models/*.js deploy/public/site/models/
cp site/avatar-styles/*.js deploy/public/site/avatar-styles/
